FROM java

LABEL maintainer "yang.by@dtwave.com"

COPY /project/dao-boot-demo-0.0.1-SNAPSHOT.jar  /usr/src/myapp/dao-boot-demo-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar $JAVA_OPTS dao-boot-demo-0.0.1-SNAPSHOT.jar